### ISSUE TITLE
How the elements are animating to make space for item being dragged

### ISSUE THREAD

**Issue by champeng** [jdbence/react-sortable-hoc#10]
@jdbence I was trying to integrate your changes with my one (which are about handling collisions or merge of items). I am almost done, but it is not working as expected when I am dropping an item for the first time into different list. It seems this animation, when an item is moved into different list, is not handled via animateNodes method. So, I am looking for the place where this is being handled. Is it simply because you are adding the item into the target list and React rendering doing the rest of the stuff? I am not able to understand what I am missing here.

**Edit:** Apologies to create an issue for a question. However, I didn't find any other way to contact you. :)

**Comment by jdbence** [comment]
@champeng Exactly, we simply add it to the list and React re-renders it. It requires the `animateNodes()` to be called at least once. This does all the list animation and it's kicked off from `handleSortMove()`.

**Comment by champeng** [comment]
Thanks @jdbence I think there is some issue with calculation of [sortingOffset.top](https://github.com/jdbence/react-sortable-hoc/blob/group/src/SortableContainer/index.js#L562) when we are moving an element from one list to the another and the first list has a scroll. It starts calculating correct values if you scroll the first list to bottom of its scroll and then move the elements to the second list.
I tried to debug it but unable to find any fruitful conclusion. However, IMO, the problem is with initialOffset being used in dragLayer. Do we need to update it (in updateTargetContainer) when there is movement to different list?

Here are the logs which made me thinking that its initialOffset that is causing the trouble.

These are before without scrolling the first list to the bottom
<pre>
0 "_DragLayer#this.currentList.initialWindowScroll.top_"
index.js?78cd:183 0 "_DragLayer#window.scrollY_"
index.js?78cd:184 {"x":611,"y":324,"pageX":611,"pageY":<b>324</b>} _DragLayer#offset_
index.js?78cd:185 {"x":478,"y":152,"pageX":478,"pageY":<b>152</b>} _DragLayer#this.initialOffset_
index.js?78cd:186 {"x":133,"y":172} _DragLayer#translate_
index.js?683d:593 {"left":393,"top":-28} _animateNodes#sortingOffset_
index.js?683d:594 {"top":110,"left":260} _animateNodes#dragLayer.offsetEdge_
index.js?683d:595 {"x":0,"y":310} _animateNodes#dragLayer.distanceBetweenContainers_
index.js?683d:596 {"x":133,"y":**172**} _animateNodes#dragLayer.translate_
index.js?683d:597 {"left":0,"top":0} _animateNodes#deltaScroll_
</pre>
These are after scrolling the first list to the bottom before moving the element.
<pre>
0 "_DragLayer#this.currentList.initialWindowScroll.top_"
index.js?78cd:183 0 "_DragLayer#window.scrollY_"
index.js?78cd:184 {"x":591,"y":352,"pageX":591,"pageY":<b>352</b>} _DragLayer#offset_
index.js?78cd:185 {"x":475,"y":130,"pageX":475,"pageY":<b>130</b>} _DragLayer#this.initialOffset_
index.js?78cd:186 {"x":116,"y":222} _DragLayer#translate_
index.js?683d:593 {"left":376,"top":2} _animateNodes#sortingOffset_
index.js?683d:594 {"top":110,"left":260} _animateNodes#dragLayer.offsetEdge_
index.js?683d:595 {"x":0,"y":330} _animateNodes#dragLayer.distanceBetweenContainers_
index.js?683d:596 {"x":116,"y":**222**} _animateNodes#dragLayer.translate_
index.js?683d:597 {"left":0,"top":0} _animateNodes#deltaScroll_
index.js?bb9b:135 onSortEn
</pre>

The items in the bold are suspect for me.

**Comment by jdbence** [comment]
@champeng Yes, we found similar results and made issue #9. I agree it's probably the offset that needs to be updated when an item is moved between lists of varying sizes and scroll positions. I suspect it's because of a race condition between the logic and render loop.

**Comment by champeng** [comment]
@jdbence good to know that you guys are already on it. Do you think there is any quick fix for that? Can I help somewhere?

**Comment by symbyte** [comment]
Something really weird is going on here. I notice that when I log out the mouse events that get received by handleStart in sortableContainer, that pageY doesn't seem to be taking the scrollable area into account.

![Weird pageY stuff](http://g.recordit.co/LWMYmQazbW.gif)

Shouldn't the last log of pageY be significantly higher than the first and second due to being at the bottom of the scrollable area? I think this might be the culprit in this of this and #9 .

**Comment by symbyte** [comment]
@jdbence The above turned out to be a red herring, but I was able to fix the offset issue from #9  and submitted a PR for it here: #11

**Comment by champeng** [comment]
Thanks @symbyte @jdbence
