### ISSUE TITLE
window-as-scrolling-container not working!

### ISSUE THREAD

**Issue by mahesh-beehively** [jdbence/react-sortable-hoc#13]
@jdbence 
I was exploring `group` branch and I must say great work done with draglayer for sorting across the list. 
However, when I use `useWindowAsScrollContainer` it looks like the window is not scrolling!

**Comment by Darcrandex** [comment]
is there some demo ?

**Comment by jdbence** [comment]
@Darcrandex This branch should be used only for a historic reference. I'd recommend going with another lib like [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)
