### ISSUE TITLE
Two Scroll Containers

### ISSUE THREAD

**Issue by TraceyK14** [jdbence/react-sortable-hoc#5]
Is it possible to have two scroll containers?

For instance like Trello, You have a List and in that list you have Tasks. Now you'll want the List container to be scrollable vertically so you can drag the tasks up and down the List container. You'll also want to drag to another list but if those lists stretch past the parent containers width there's no way to drag the tasks to the other lists off the screen. You'd have to drag the task to the last visible List and then manually scroll the parent container horizontally and then pick the task back up and drag it to the desired list.

If not I can do it myself, but I thought I'd ask before I do.

**Comment by DimitarNestorov** [comment]
> Is it possible to have two scroll containers?

It is.

> You'll also want to drag to another list but if those lists stretch past the parent containers width there's no way to drag the tasks to the other lists off the screen. 

It's pretty easy to be implemented (onDragStart listen for the mouse position being near the container edges and scroll them), but I don't think it should be included in this library.

To implement this in the library would require the lists to be held in another container like it was before, defeating the purpose of the DragLayer resulting in other issues.

**Comment by jdbence** [comment]
I'll close this for now. If its a need for the project, it should come in as another PR

**Comment by TraceyK14** [comment]
@dimitarnestorov Yea that's what I was thinking I would have to do but I figured I would ask first. Thank you for your answer.
