### ISSUE TITLE
Dragging an item into a list that contains no items.

### ISSUE THREAD

**Issue by TraceyK14** [jdbence/react-sortable-hoc#7]
If you drag an item from one list into another and the destination list is empty to begin with it throws this error. 

```
Uncaught TypeError: Cannot read property 'slice' of null
    at arrayInsert 
    at onSortSwap 
    at _class._this.handleSortSwap 
    at onSortEnd 
    at _class._this.handleSortEnd 
    at DragLayer.updateTargetContainer 
    at DragLayer.handleSortMove 

Uncaught TypeError: Cannot read property 'item' of null
    at DragLayer.updateTargetContainer 
    at DragLayer.handleSortMove 
```

**Comment by jdbence** [comment]
@TraceyK14 I've tried this and it works fine if you set the default value of the items to an empty array. In your error response, it says it's null.

**Comment by TraceyK14** [comment]
@jdbence Wow, that's my fault.  You're correct, It works if you set it to an empty array. Sorry about that.
